sudo: required
language: python
services:
- docker
python:
- 3.6

before_install:
  - "./travis/az-repo.bash"
  - "./travis/install-git-crypt.bash"
  - "./travis/install-kubectl.bash"
  - "./travis/install-helm.bash"
  - sudo apt-get install jq

install:
  - pip install --no-cache-dir pyyaml

script:
- "./travis/travis-script.bash build"

branches:
  only:
    - staging
    - prod

deploy:
  provider: script
  script: ./travis/travis-script.bash deploy
  on:
    branch:
      - staging
      - prod

env:
  global:
    - AZ_LOCATION: "westus2"
    - CLUSTER_ADMIN: "datahub"
    - HUB_COURSE: "data100"
    - SUBSCRIPTION_PREFIX: "data100-18sp"
    - secure: "l+uUR+uLq0dyLm9GXDWz48u+tBFFlGabiixPoENTcP9Zp0qxJNpSFeKr1E1YDxii4MFFgsbIxCqiBlhM68LC27tCIyiUm88gK+WTXRLL5eWna7ddnuOZ41dhhZxabrorjKsEQe+nSKAdrjEWk1RsnSfmvMS1NFEidtElK/qlvn7KQTr6AEqOEjJChiczct35pD81p4Ipej63OpqvnvFHgdvcD6h4qlNa2Ks/FWHP3RWmG3j5pytFEFIv5Q6Fiq6o7S97b7wuSyPPpW990qWORkoWciG/qtz8SKRz3UfVxWstaQyU6CJUCyK+fA9S6Aig2zlPnmX+Aq3Cj6+8sb0Ghdu5r3gUu4yJHi1kx3WBMIG9elIzb7EOoHeIRz5tcHpuWosHh05dWgHyIzI3A59umNrmpQE1jPkV7eHkq5njYAu/ljMeMtr1+/ogGZhxkyuXRhdidIZcCCkrIoFS3qUdPPeqi2/ir5i+XUl3U4kjlH3S3yZGvOoSW4K7jgaqz9zaXeoJ7mDYO5f/v4VGPnJY3on3EUQUncvr9zhOR67N7nQAE3vsvc3ngD6WSyES0ZnZAz5gglNgzOLEIsRHv1xhKRIMVDnuGsm5dc+1r7j7kveyJ/mJcdWhWXJeG5FTjUaAv7oC07fwMhNZF7dPGwKDZEGI1AaFQfNY6vXWbg7w8TE="
    - secure: "FsB3a4s4NJneXQNE4TWc4Ko40ecK9JntusRpkaS6vW7412nYOr1gIIHu7P88YzHxiJ2gnzlavn7P42NqGe3Dc1Jv+0ky4NCFoeXDYb3AAKr7u7VOYgZPoahj70oLm59AgBof2XfmiJPGDiBByCyVhq/gJX0k4fMWlgGkH5/h3lrbDPO8bQwuW/LZh3qx2McI0rYKr0QOkM2AFsOLCwd1uW19P/dvjZJ2Prvff1Hay0mJagQ2x8PTqguOCRylUD/OAW2fjpu2s1yB4cXBEcUm1GKwYUHYGjkeCh2P1SI1P5KPDwOM5pclVy59OR16pCdHnZ8mLPK4bHy41zAHzSz1nDF/Ski/2YN4H2wQV6sgK+xHe/HX6KYUqPpAAf8Zf+arNgXtoq1NAzw6/zFFfedoHM/NPipMzjBbUzkWgxIKCNIqgsGSyY06lArDF2MoPhsGINK87M3p6qM/rbDdPx45bdvhSqrB1yFnQRcAY92mUXgpPhLRPX9AD7YEycHQVQ1QYxFColx0mDNHRsQaOy4wcVINkuoyhNHYmVhsrKse2bKJOpY+oiYtDedwNO9f+VDVBe4/yw/DF3roiSL6tt9fHItHV43ip78V2xUuURC+c3CYggZEYrFXZMRqhgE7XPqEORQCzzInQRuD/pf5sqHq8R7aiZi1mpG3s8R9u/ig0tI="

