version: "v0.6.0"

rbac:
  enabled: true

#prePuller:
#  enabled: true
#  image:
#    name: ryanlovett/image-allnodes-puller
#    tag: 242d8db

hub:
  extraConfig: |
    from kubespawner import KubeSpawner
    from tornado import gen
    import yaml

    class CustomKubeSpawner(KubeSpawner):
      @gen.coroutine
      def start(self):
        with open('/etc/jupyterhub/config/custom.memory') as f:
          custom_attr_lists = yaml.safe_load(f)
          for attr, users in custom_attr_lists.items():
            if self.user.name in users:
              self.mem_limit = attr
              self.mem_guarantee = attr
              break

        with open('/etc/jupyterhub/config/custom.image') as f:
          custom_attr_lists = yaml.safe_load(f)
          for attr, users in custom_attr_lists.items():
            if self.user.name in users:
              self.singleuser_image_spec = attr
              break

        with open('/etc/jupyterhub/config/custom.volumes') as f:
          custom_attr_lists = yaml.safe_load(f)
          for name, volume in custom_attr_lists.items():
            if self.user.name in volume['users']:
              self.singleuser.volumes.append({
                'name':name, 'hostPath': volume['hostPath']
                })
              self.singleuser.volume_mounts.append({
                'name':name, 'mountPath', volume['mountPath']
                })
              break

        return (yield super().start())
    c.JupyterHub.spawner_class = CustomKubeSpawner

cull:
  enabled: true
  timeout: 3600 # default

auth:
  type: google

singleuser:
  memory:
    guarantee: 2G
    limit: 2G
  image:
    name: "berkeleydsep/singleuser-data100"
  storage:
    type: hostPath
    extraVolumes:
      - name: home
        hostPath:
          path: /data/homes/{username}
      - name: nbgrader
        hostPath:
          path: /data/homes/_nbgrader
    extraVolumeMounts:
      - name: home
        mountPath: /home/jovyan
      - name: nbgrader
        mountPath: /srv/nbgrader
